/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.cadastrar;

import GUI.*;
import modelo.Funcionario;
import DAO.FuncionarioDAO;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

import java.text.SimpleDateFormat;

import java.awt.Graphics;

/**
 *
 * @author Carlos
 */
public class FuncionarioC extends javax.swing.JInternalFrame {

    /**
     * Creates new form Funcionario
     */
    public FuncionarioC() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        FuncionarioDAO pdao = new FuncionarioDAO();
        
        for(Funcionario f: pdao.read()){
            
            modelo.addRow(new Object[]{
            
            f.getId_funcionario(),
            f.getNome_funcionario(),
            f.getCpf_funcionario(),
            f.getRg_funcionario(),
            f.getEmail_funcionario(),
            f.getEndereco_funcionario(),
            f.getTelefone_funcionario(),
            f.getTelefone2_funcionario(),
            f.getIdade_funcionario(),
            f.getData_nascimento_funcionario(),
            f.getSexo_funcionario(),
            f.getTurno(),
            f.getCargo(),
            f.getSalario(),
            f.getFoto_funcionario()
            
            });
        
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        sexo = new javax.swing.JComboBox<>();
        cargo = new javax.swing.JComboBox<>();
        turno = new javax.swing.JComboBox<>();
        cpf = new javax.swing.JFormattedTextField();
        rg = new javax.swing.JFormattedTextField();
        tel = new javax.swing.JFormattedTextField();
        tel2 = new javax.swing.JFormattedTextField();
        data = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salvar = new javax.swing.JButton();
        sala = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1290, 730));
        setPreferredSize(new java.awt.Dimension(1290, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 92, 270, 30));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 270, 30));
        getContentPane().add(idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 322, 270, 30));
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 250, 30));
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 152, 200, 30));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        getContentPane().add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 270, 30));

        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa", "Estoquista", "Gerente", "Gestor", "Serviços Gerais", "Vendedor" }));
        getContentPane().add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 250, 30));

        turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde" }));
        getContentPane().add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 250, 30));

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 270, 30));

        try {
            rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 262, 270, 30));

        try {
            tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 152, 250, 30));

        try {
            tel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 202, 250, 30));

        data.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 92, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "Email", "Endereço", "Telefone", "Telefone2", "Idade", "Data_nascimento", "Sexo", "Turno", "Cargo", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 810, 230));

        salvar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        salvar.setText("Salvar");
        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarMouseClicked(evt);
            }
        });
        getContentPane().add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 230, 90));
        getContentPane().add(sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 102, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Funcionario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseClicked
    Funcionario funcionario = new Funcionario();
       FuncionarioDAO dao = new FuncionarioDAO();
       
       funcionario.setNome_funcionario(nome.getText());
       funcionario.setCpf_funcionario(cpf.getText());
       funcionario.setRg_funcionario(rg.getText());
       funcionario.setEmail_funcionario(email.getText());
       funcionario.setEndereco_funcionario(endereco.getText());
       funcionario.setTelefone_funcionario(tel.getText());
       funcionario.setTelefone2_funcionario(tel2.getText());
       funcionario.setIdade_funcionario(Integer.parseInt(idade.getText()));
       funcionario.setSexo_funcionario(sexo.getSelectedItem().toString());
       funcionario.setTurno(turno.getSelectedItem().toString());
       funcionario.setCargo(cargo.getSelectedItem().toString());
       funcionario.setSalario(Double.parseDouble(sala.getText()));
       dao.salvar(funcionario);
       
       nome.setText("");
       cpf.setText("");
       rg.setText("");
       email.setText("");
       endereco.setText("");
       tel.setText("");
       tel2.setText("");
       idade.setText("");
       sexo.setSelectedItem("null");
       turno.setSelectedItem("null");
       cargo.setSelectedItem("null");
       sala.setText("");
       
       readJTable();
    }//GEN-LAST:event_salvarMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      if (jTable1.getSelectedRow() != -1) {
      
        nome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        cpf.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        rg.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        email.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        endereco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        tel.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        tel2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        idade.setText(jTable1.getValueAt(jTable1.getSelectedRow(),8).toString());
        sexo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),9).toString());    
        turno.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),10).toString());
        cargo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),11).toString());
        sala.setText(jTable1.getValueAt(jTable1.getSelectedRow(),12).toString()); 
      }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (jTable1.getSelectedRow() != -1) {
      
        nome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        cpf.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        rg.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        email.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        endereco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        tel.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        tel2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        idade.setText(jTable1.getValueAt(jTable1.getSelectedRow(),8).toString());
        sexo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),9).toString());    
        turno.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),10).toString());
        cargo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),11).toString());
        sala.setText(jTable1.getValueAt(jTable1.getSelectedRow(),12).toString()); 
      }
    }//GEN-LAST:event_jTable1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JFormattedTextField cpf;
    private com.toedter.calendar.JDateChooser data;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.JTextField sala;
    private javax.swing.JButton salvar;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JFormattedTextField tel;
    private javax.swing.JFormattedTextField tel2;
    private javax.swing.JComboBox<String> turno;
    // End of variables declaration//GEN-END:variables
}
