/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.*;
import DAO.*;
        

/**
 *
 * @author Carlos
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/door_in.png"))); // NOI18N
        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/door_out.png"))); // NOI18N
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, -1));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, 30));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 172, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
      dispose();
    }//GEN-LAST:event_sairMouseClicked

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
String nome = usuario.getText();
        String senha = txtSenha.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        try (Connection con = (Connection) 
                
                DriverManager.getConnection("jdbc:mysql://localhost/bdapolo","root", ""); 
                Statement stmt = (Statement) con.createStatement()) {

            String query = "select * from funcionario where nome_funcionario = '"+nome+"' and senha = '"+senha+"'";

                try (ResultSet rs = stmt.executeQuery(query)) {
                    if (rs.next()) {
                        int id_funcionário = rs.getInt("id_funcionário");
                        
                                   
                        if(id_funcionário == 1){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        
                        if(id_funcionário == 2){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        if(id_funcionário == 3){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        
                        if(id_funcionário == 4){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        if(id_funcionário == 5){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        
                        if(id_funcionário == 6){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        if(id_funcionário == 7){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                        
                        if(id_funcionário == 8){
                            JOptionPane.showMessageDialog(null,"Conectado com sucesso");
                            Menu s = new Menu();
                            
                            s.setVisible(true);
                            this.dispose();
                        }
                    }
                    

                    else {
                        JOptionPane.showMessageDialog(null,"Usuário e/ou senha incorretos.");
                        usuario.setText("");
                        txtSenha.setText("");
                    }   } catch (PropertyVetoException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
      
       
        }
        } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }//GEN-LAST:event_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sair;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
