
package GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import GUI.cadastrar.*;
import GUI.Alterar.*;
import GUI.excluir.*;
/**
 *
 * @author Carlos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     * @throws java.beans.PropertyVetoException
     */
    public Menu() throws PropertyVetoException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/MenuFundo.jpeg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        a = new javax.swing.JMenu();
        ClienteC = new javax.swing.JMenuItem();
        ClienteE = new javax.swing.JMenuItem();
        ClienteD = new javax.swing.JMenuItem();
        VisuC = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        FunciC = new javax.swing.JMenuItem();
        FunciE = new javax.swing.JMenuItem();
        FunciD = new javax.swing.JMenuItem();
        VisuF = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ProC = new javax.swing.JMenuItem();
        ProE = new javax.swing.JMenuItem();
        ProD = new javax.swing.JMenuItem();
        VisuP = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Descon = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group.png"))); // NOI18N
        a.setText("Cliente");

        ClienteC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group_add.png"))); // NOI18N
        ClienteC.setText("Cadastrar");
        ClienteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCActionPerformed(evt);
            }
        });
        a.add(ClienteC);

        ClienteE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group_edit.png"))); // NOI18N
        ClienteE.setText("Editar");
        ClienteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteEActionPerformed(evt);
            }
        });
        a.add(ClienteE);

        ClienteD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group_delete.png"))); // NOI18N
        ClienteD.setText("Deletar");
        ClienteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteDActionPerformed(evt);
            }
        });
        a.add(ClienteD);

        VisuC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        VisuC.setText("Visualizar");
        a.add(VisuC);

        jMenuBar1.add(a);

        Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        Estoque.setText("Estoque");

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        jMenuItem13.setText("Visualizar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Estoque.add(jMenuItem13);

        jMenuBar1.add(Estoque);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        jMenu3.setText("Funcionário");

        FunciC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_add.png"))); // NOI18N
        FunciC.setText("Cadastrar");
        FunciC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunciCActionPerformed(evt);
            }
        });
        jMenu3.add(FunciC);

        FunciE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_edit.png"))); // NOI18N
        FunciE.setText("Editar");
        FunciE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunciEActionPerformed(evt);
            }
        });
        jMenu3.add(FunciE);

        FunciD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_delete.png"))); // NOI18N
        FunciD.setText("Deletar");
        FunciD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunciDActionPerformed(evt);
            }
        });
        jMenu3.add(FunciD);

        VisuF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        VisuF.setText("Visualizar");
        jMenu3.add(VisuF);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cart.png"))); // NOI18N
        jMenu4.setText("Produto");

        ProC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cart_add.png"))); // NOI18N
        ProC.setText("Cadastrar");
        ProC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProCActionPerformed(evt);
            }
        });
        jMenu4.add(ProC);

        ProE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cart_edit.png"))); // NOI18N
        ProE.setText("Editar");
        ProE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProEActionPerformed(evt);
            }
        });
        jMenu4.add(ProE);

        ProD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cart_delete.png"))); // NOI18N
        ProD.setText("Deletar");
        ProD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProDActionPerformed(evt);
            }
        });
        jMenu4.add(ProD);

        VisuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        VisuP.setText("Visualizar");
        jMenu4.add(VisuP);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Venda");

        jMenuItem1.setText("Relatório");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Efetuar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        Descon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/door_out.png"))); // NOI18N
        Descon.setText("Desconectar");
        Descon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesconMouseClicked(evt);
            }
        });
        jMenuBar1.add(Descon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DesconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesconMouseClicked
        dispose();
        Login t = new Login();
        t.setVisible(true);
    }//GEN-LAST:event_DesconMouseClicked

    private void ClienteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteCActionPerformed
    ClienteC t = new ClienteC();
      jDesktopPane1.add(t);
      t.setVisible(true);   
    }//GEN-LAST:event_ClienteCActionPerformed

    private void ClienteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteEActionPerformed
      ClienteA t = new ClienteA();
      jDesktopPane1.add(t);
      t.setVisible(true); 
    }//GEN-LAST:event_ClienteEActionPerformed

    private void FunciEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunciEActionPerformed
      FuncionarioA t = new FuncionarioA();
      jDesktopPane1.add(t);
      t.setVisible(true);         
    }//GEN-LAST:event_FunciEActionPerformed

    private void FunciCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunciCActionPerformed
    FuncionarioC t = new FuncionarioC();
      jDesktopPane1.add(t);
      t.setVisible(true);
    }//GEN-LAST:event_FunciCActionPerformed

    private void ProCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProCActionPerformed
      ProdutoC t = new ProdutoC();
      jDesktopPane1.add(t);
      t.setVisible(true);        
    }//GEN-LAST:event_ProCActionPerformed

    private void ProEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProEActionPerformed
      ProdutoA t = new ProdutoA();
      jDesktopPane1.add(t);
      t.setVisible(true);
    }//GEN-LAST:event_ProEActionPerformed

    private void ClienteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteDActionPerformed
      ClienteE t = new ClienteE();
      jDesktopPane1.add(t);
      t.setVisible(true);   
    }//GEN-LAST:event_ClienteDActionPerformed

    private void FunciDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunciDActionPerformed
      FuncionarioE t = new FuncionarioE();
      jDesktopPane1.add(t);
      t.setVisible(true);   
    }//GEN-LAST:event_FunciDActionPerformed

    private void ProDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProDActionPerformed
      ProdutoE t = new ProdutoE();
      jDesktopPane1.add(t);
      t.setVisible(true);   
    }//GEN-LAST:event_ProDActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
     Estoque t = new Estoque();
      jDesktopPane1.add(t);
      t.setVisible(true);   
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      Relatorio t = new Relatorio();
      jDesktopPane1.add(t);
      t.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Efetuar t = new Efetuar();
      jDesktopPane1.add(t);
      t.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Menu().setVisible(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteC;
    private javax.swing.JMenuItem ClienteD;
    private javax.swing.JMenuItem ClienteE;
    private javax.swing.JMenu Descon;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenuItem FunciC;
    private javax.swing.JMenuItem FunciD;
    private javax.swing.JMenuItem FunciE;
    private javax.swing.JMenuItem ProC;
    private javax.swing.JMenuItem ProD;
    private javax.swing.JMenuItem ProE;
    private javax.swing.JMenuItem VisuC;
    private javax.swing.JMenuItem VisuF;
    private javax.swing.JMenuItem VisuP;
    private javax.swing.JMenu a;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
