
package GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Carlos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     * @throws java.beans.PropertyVetoException
     */
    public Menu() throws PropertyVetoException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/fundo_menu.png"));
        Image image = icon.getImage();
        Menu = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        cli = new javax.swing.JMenu();
        Estoque = new javax.swing.JMenu();
        Funcionario = new javax.swing.JMenu();
        Produto = new javax.swing.JMenu();
        Venda = new javax.swing.JMenu();
        Descon = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(489, 30));

        cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group.png"))); // NOI18N
        cli.setText("Cliente");
        cli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliMouseClicked(evt);
            }
        });
        jMenuBar1.add(cli);

        Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        Estoque.setText("Estoque");
        Estoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstoqueMouseClicked(evt);
            }
        });
        jMenuBar1.add(Estoque);

        Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        Funcionario.setText("Funcionário");
        Funcionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuncionarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(Funcionario);

        Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cart.png"))); // NOI18N
        Produto.setText("Produto");
        Produto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutoMouseClicked(evt);
            }
        });
        jMenuBar1.add(Produto);

        Venda.setText("Venda");
        Venda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VendaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Venda);

        Descon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/door_out.png"))); // NOI18N
        Descon.setText("Desconectar");
        Descon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesconMouseClicked(evt);
            }
        });
        jMenuBar1.add(Descon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DesconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesconMouseClicked
        dispose();
        Login t = new Login();
        t.setVisible(true);
    }//GEN-LAST:event_DesconMouseClicked

    private void FuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuncionarioMouseClicked
       funcionario f = new funcionario();
       Menu.add(f);
       f.setVisible(true);
        f.show();
        try {
        f.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_FuncionarioMouseClicked

    private void cliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliMouseClicked
    cliente c = new cliente();
    Menu.add(c);
    c.setVisible(true);
    c.show();
    try{
    c.setMaximum(true);
    } catch (PropertyVetoException ex){
    }
    }//GEN-LAST:event_cliMouseClicked

    private void EstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstoqueMouseClicked
       estoque e = new estoque();
        Menu.add(e);
        e.setVisible(true);
        e.show();
        try {
            e.setMaximum(true);
        } catch (PropertyVetoException ex) {
            
        }
    }//GEN-LAST:event_EstoqueMouseClicked

    private void ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutoMouseClicked
        produto p = new produto();
        Menu.add(p);
        p.setVisible(true);
        p.show();
        try {
            p.setMaximum(true);
        } catch (PropertyVetoException ex) {
            
        }
    }//GEN-LAST:event_ProdutoMouseClicked

    private void VendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_VendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Menu().setVisible(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Descon;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenu Funcionario;
    private javax.swing.JDesktopPane Menu;
    private javax.swing.JMenu Produto;
    private javax.swing.JMenu Venda;
    private javax.swing.JMenu cli;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
