
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.Alterar;

import GUI.cadastrar.*;
import GUI.*;
import modelo.Produto;
import DAO.ProdutoDAO;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

import java.text.SimpleDateFormat;

import java.awt.Graphics;
import javax.swing.JFileChooser;

/**
 *
 * @author Carlos
 */
public class ProdutoA extends javax.swing.JInternalFrame {

    /**
     * Creates new form Produto
     */
    public ProdutoA() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produto p: pdao.read()){
            
            modelo.addRow(new Object[]{
            
             p.getId_produto(),
             p.getCodigo_produto(),
             p.getNome_produto(),
             p.getNome_fornecedor(),
             p.getData_registro(),
             p.getCategoria(),
             p.getQuantidade(),
             p.getPreco_produto(),
             p.getPreco_compra(),
             p.getDesconto()
            
            });
        
        }}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        fornecedor = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        tamanho = new javax.swing.JTextField();
        quant = new javax.swing.JTextField();
        data = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        preco = new javax.swing.JTextField();
        precop = new javax.swing.JTextField();
        desconto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1292, 756));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 260, 30));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 260, 30));
        getContentPane().add(fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 260, 30));
        getContentPane().add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 260, 30));
        getContentPane().add(tamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 260, 30));
        getContentPane().add(quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 300, 30));

        data.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 300, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Produto", "Fornecedor", "Data_Registro", "Categoria", "Quantidade", "Tamanho", "Preco_Produto", "Preco_Compra", "Desconto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 790, 250));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 120, 60));
        getContentPane().add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 242, 300, 30));
        getContentPane().add(precop, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 300, 30));
        getContentPane().add(desconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Produto.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable1.getSelectedRow() != -1) {
        Produto produto = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        produto.setNome_produto(nome.getText());
        produto.setNome_fornecedor(fornecedor.getText());
        produto.setCodigo_produto(Integer.parseInt(codigo.getText()));
        produto.setData_registro(data.getDate());
        produto.setCategoria(categoria.getText());
        produto.setQuantidade(Integer.parseInt(quant.getText()));
        produto.setTamanho(tamanho.getText());
        produto.setPreco_produto(Double.parseDouble(precop.getText()));
        produto.setPreco_compra(Double.parseDouble(preco.getText()));
        produto.setDesconto(Integer.parseInt(desconto.getText()));
        dao.atualizar(produto);
        
        nome.setText("");
        fornecedor.setText("");
        codigo.setText("");
        data.setDateFormatString("");
        quant.setText("");
        tamanho.setText("");
        precop.setText("");
        preco.setText("");
        desconto.setText("");
        
        readJTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (jTable1.getSelectedRow() != -1) {
        
        nome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        fornecedor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        codigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        data.setDateFormatString(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
        categoria.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        quant.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        tamanho.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        precop.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        preco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        desconto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    if (jTable1.getSelectedRow() != -1) {
        
        nome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        fornecedor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        codigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        data.setDateFormatString(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
        categoria.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        quant.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        tamanho.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        precop.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        preco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        desconto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField codigo;
    private com.toedter.calendar.JDateChooser data;
    private javax.swing.JTextField desconto;
    private javax.swing.JTextField fornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField precop;
    private javax.swing.JTextField quant;
    private javax.swing.JTextField tamanho;
    // End of variables declaration//GEN-END:variables
}
